#!/usr/bin/env perl -w

use strict;

my ($n, $file) = @ARGV;
unless (defined $n and defined $file and $n =~ /^\d+$/ and -e $file) { 
  die "Sample usage: $0 10 /usr/share/dict/words\n"; 
}

my @line; 

open my $fh, '<', $file or die $!;
while (<$fh>) {
  if ((int rand $.) <= $n) {
    if (@line < $n) {
      push @line, $_;
    } else {
      $line[rand $n] = $_;
    }
  }
}
close $fh or die $!;

for my $s (@line) {
  print $s;
}
